# The values in this config are usable with https://github.com/moneroexamples/private-testnet

hash_type="cryptonight"
# If this is turned up to "debug", tokio in particular gives a lot of helpful debugging in
log_level="info"
log_file="cryptosmelt.log"

influx_url="http://localhost:8086"
daemon_url="http://localhost:38081/json_rpc"
wallet_url="http://localhost:38082/json_rpc"

payment_mixin=2
min_payment=0.1
payment_denomination=0.01
pool_wallet="9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8"
pool_fee=1.0

[[donations]]
address="Wmsof1vqt9Z23bfggkVXDscRgkcyejvvDTuWi7AMtjnNaod9SrwqrNQDPzRRDrxA7BAirbySZY9V6K7EPU4A2zzG2D2msfxGX"
percentage=1.0

[[ports]]
port = 11336
starting_difficulty = 50
target_time = 10

[[ports]]
port = 11337
starting_difficulty = 500
target_time = 10

[[ports]]
port = 11338
starting_difficulty = 5000
target_time = 10